### ISSUE TITLE
Error: size mismatch for transformer.embed_tgt.weight: copying a param with shape torch.Size([232, 256]) from checkpoint, the shape in current model is torch.Size([233, 256])

### ISSUE THREAD

**Issue by titikid** [pbcquoc/vietocr#6]
Hi a Quốc, em đang test model của anh theo code bên dưới thì gặp lỗi sau:

```
Traceback (most recent call last):
  File "/home/duycuong/PycharmProjects/research_py3/text_recognition/classifier/vietocr/vietocr_gettingstart.py", line 13, in <module>
    detector = Predictor(config)
  File "/home/duycuong/PycharmProjects/research_py3/text_recognition/classifier/vietocr/vietocr/tool/predictor.py", line 19, in __init__
    model.load_state_dict(torch.load(weights, map_location=torch.device(device)))
  File "/home/duycuong/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 839, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for VietOCR:
	size mismatch for transformer.embed_tgt.weight: copying a param with shape torch.Size([232, 256]) from checkpoint, the shape in current model is torch.Size([233, 256]).
	size mismatch for transformer.fc.weight: copying a param with shape torch.Size([232, 256]) from checkpoint, the shape in current model is torch.Size([233, 256]).
	size mismatch for transformer.fc.bias: copying a param with shape torch.Size([232]) from checkpoint, the shape in current model is torch.Size([233]).
```
Đây là code em chạy

```
from PIL import Image
from vietocr.tool.predictor import Predictor
from vietocr.tool.config import Cfg

config = Cfg.load_config_from_name('vgg_transformer')

config['device'] = 'cuda:0'
config['predictor']['beamsearch']=False
detector = Predictor(config)
```

**Comment by pbcquoc** [comment]
Hi e, nhớ install đúng version nhé. 

pip install vietocr==0.1.9

**Comment by titikid** [comment]
Tks anh, em chạy đc rồi

**Comment by ngochoai2001** [comment]
> Hi e, nhớ install đúng version nhé.
> 
> pip install vietocr==0.1.9

a ơi em bị lỗi trên khi sau khi train, weights load từ weights/transformerocr.pth
![image](https://github.com/pbcquoc/vietocr/assets/60635339/adace5d5-f43b-4e38-9e03-9d6420315852)
