### ISSUE TITLE
Lỗi về Vocab 

### ISSUE THREAD

**Issue by hoainam-nguyen** [pbcquoc/vietocr#66]
Em gặp lỗi như bên dưới khi thử train lại bằng new data. Nhờ anh hỗ trợ fix lỗi ạ

`KeyError: Caught KeyError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "./vietocr/vietocr/loader/dataloader.py", line 111, in __getitem__
    img, word, img_path = self.read_data(idx)
  File "./vietocr/vietocr/loader/dataloader.py", line 106, in read_data
    word = self.vocab.encode(label)
  File "./vietocr/vietocr/model/vocab.py", line 20, in encode
    return [self.go] + [self.c2i[c] for c in chars] + [self.eos]
  File "./vietocr/vietocr/model/vocab.py", line 20, in <listcomp>
    return [self.go] + [self.c2i[c] for c in chars] + [self.eos]
KeyError: '°'`

**Comment by pbcquoc** [comment]
Hi e, 
Mình đã định nghĩa sẵn tập kí tự mà mô hình nhận dạng ở config['vocab'] 
KeyError: '°' kí tự này ko có trong tập vocab nhé e. Dữ liệu e nên tiền xử lý bớt nhiễu hoặc kí tự đó cần thiết thì e tự bổ sung thêm vào tập vocab nhé.
