### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by Littlehead27** [pbcquoc/vietocr#83]
File "train.py", line 35, in <module>
    trainer = Trainer(config, pretrained=True)
  File "/data1/jupyter/anhai/vietocr0/vietocr/model/trainer.py", line 78, in __init__
    self.train_gen = self.data_gen('train_{}'.format(self.dataset_name), 
  File "/data1/jupyter/anhai/vietocr0/vietocr/model/trainer.py", line 310, in data_gen
    dataset = OCRDataset(lmdb_path=lmdb_path, 
  File "/data1/jupyter/anhai/vietocr0/vietocr/loader/dataloader.py", line 39, in __init__
    createDataset(self.lmdb_path, root_dir, annotation_path)
  File "/data1/jupyter/anhai/vietocr0/vietocr/tool/create_dataset.py", line 55, in createDataset
    imageFile, label = annotations[i]
ValueError: too many values to unpack (expected 2)

**Comment by pbcquoc** [comment]
Pls check your annotation file.

**Comment by Littlehead27** [comment]
> 请检查您的注释文件。

Could you tell me which file it is?

**Comment by Littlehead27** [comment]
> 请检查您的注释文件。

I've already checked, but I put in another mistake

**Comment by Littlehead27** [comment]
Traceback (most recent call last):
  File "train.py", line 36, in <module>
    trainer.visualize_dataset()
  File "/data1/jupyter/anhai/vietocr0/vietocr/model/trainer.py", line 239, in visualize_dataset
    for batch in self.train_gen:
  File "/home/work/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/work/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/work/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
label: 010201004678
label: Ấp Đá Chổng
    data.reraise()
  File "/home/work/.local/lib/python3.8/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/work/.local/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/work/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/work/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data1/jupyter/anhai/vietocr0/vietocr/loader/dataloader.py", line 109, in __getitem__
    img, word, img_path = self.read_data(idx)
  File "/data1/jupyter/anhai/vietocr0/vietocr/loader/dataloader.py", line 104, in read_data
    word = self.vocab.encode(label)
  File "/data1/jupyter/anhai/vietocr0/vietocr/model/vocab.py", line 20, in encode
    return [self.go] + [self.c2i[c] for c in chars] + [self.eos]
  File "/data1/jupyter/anhai/vietocr0/vietocr/model/vocab.py", line 20, in <listcomp>
    return [self.go] + [self.c2i[c] for c in chars] + [self.eos]
KeyError: '̣'

**Comment by pbcquoc** [comment]
Hi
make sure that every characters in your vocab is included in config['vocab']
