### ISSUE TITLE
ModuleNotFoundError: No module named 'vietocr.loader.DataLoader'

### ISSUE THREAD

**Issue by vnlebaoduy** [pbcquoc/vietocr#9]
Bạn ơi bạn có thể check giúp mình lỗi này được ko ạ. Khi mình chạy version 0.1.9 thì bị lỗi này. Mình check trong code thì báo lỗi dòng này "from vietocr.loader.DataLoader import DataGen"

```
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from vietocr.model.trainer import Trainer
  File "/Volumes/DATA/STUDY/AI/Buoi05/DetectHand2/lib/python3.7/site-packages/vietocr/model/trainer.py", line 11, in <module>
    from vietocr.loader.DataLoader import DataGen

```

**Comment by vnlebaoduy** [comment]
Lỗi này chỉ bị trên Mac. Do đặt tên giống nhau và trên Mac không phân biệt hoa thường nên file bị missing
